CREATE TABLE userInfo (firstName varchar(10) NOT NULL UNIQUE,
                       lastName varchar(15) NOT NULL,
                       username VARCHAR(30) NOT NULL ,
                       password VARCHAR(30) NOT NULL , 
                       birth_date DATE NOT NULL, 
                       email VARCHAR(320) NOT NULL , 
                       Address    VARCHAR(120),
                       City        VARCHAR(100) NOT NULL,
                       State       CHAR(2) NOT NULL,
                       Country     CHAR(100) NOT NULL,
                       PostalCode  VARCHAR(16) NOT NULL,
                       userType VARCHAR(16) NOT NULL,
                       promotion INT(20) NOT NULL,
                       verification_code INT(20) NOT NULL,
                       email_verified_at DATETIME NULL,
                       verified INT NOT NULL,
                       PRIMARY KEY (username));